import {
  A2ACommandMesh,
  AgentBazaarExchange,
  AtlasFoundry,
  BazaarCodexAtlas,
  ConvergenceLedger,
  HyperOpsWarp,
  LiquidityOptimizer,
  MeshTelemetry,
  NexusExchange,
  OmniNetworkHub,
  PolicyEngine,
  PolicyForge,
  QuantumSettlement,
  SentinelVault,
  SovereignOpsCitadel,
  SovereignRiskCenter,
  StrategyLab,
  SwarmStudio,
  TrustGraph,
  VelocitySanctum,
} from "./pages";

export const routes = [
  { path: "/", element: SovereignRiskCenter, name: "Sovereign Risk Center" },
  { path: "/sovereign-risk", element: SovereignRiskCenter, name: "Sovereign Risk Center" },
  { path: "/liquidity-optimizer", element: LiquidityOptimizer, name: "Liquidity Optimizer" },
  { path: "/trust-graph", element: TrustGraph, name: "Trust Graph" },
  { path: "/strategy-lab", element: StrategyLab, name: "AI Strategy Lab" },
  { path: "/policy-engine", element: PolicyEngine, name: "Policy Engine" },
  { path: "/omni-network", element: OmniNetworkHub, name: "Omni-Network Hub" },
  { path: "/a2a-command-mesh", element: A2ACommandMesh, name: "A2A Command Mesh" },
  { path: "/bazaar-codex", element: BazaarCodexAtlas, name: "Bazaar Codex Atlas" },
  { path: "/hyperops-warp", element: HyperOpsWarp, name: "HyperOps Warp" },
  { path: "/sentinel-vault", element: SentinelVault, name: "Sentinel Vault" },
  { path: "/mesh-telemetry", element: MeshTelemetry, name: "Mesh Telemetry" },
  { path: "/quantum-settlement", element: QuantumSettlement, name: "Quantum Settlement" },
  { path: "/policy-forge", element: PolicyForge, name: "Policy Forge" },
  { path: "/swarm-studio", element: SwarmStudio, name: "Swarm Studio" },
  { path: "/nexus-exchange", element: NexusExchange, name: "Nexus Exchange" },
  { path: "/atlas-foundry", element: AtlasFoundry, name: "Atlas Foundry" },
  { path: "/ops-citadel", element: SovereignOpsCitadel, name: "Sovereign Ops Citadel" },
  { path: "/convergence-ledger", element: ConvergenceLedger, name: "Convergence Ledger" },
  { path: "/agent-bazaar", element: AgentBazaarExchange, name: "Agent Bazaar Exchange" },
  { path: "/velocity-sanctum", element: VelocitySanctum, name: "Velocity Sanctum" },
];
